---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fnelhuxtks/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index.*.js $DEPLOYPATH
    - /bin/cp index.*.css $DEPLOYPATH
    - /bin/cp *.png $DEPLOYPATH
    - /bin/cp *.jpg $DEPLOYPATH
    - /bin/cp *.map $DEPLOYPATH
